### PR TITLE
Implement Unicode Line Breaking Algorithm

### LINKED ISSUE #103: WrappingWidth Not Work in those languages not use whitespace as word separator
At https://github.com/SixLabors/Fonts/blob/master/src/SixLabors.Fonts/TextLayout.cs#L114

```
if (options.WrappingWidth > 0 && char.IsWhiteSpace(text[i]))
{
    ...
}
```

Languages like **Chinese**, do not use **WhiteSpace** as word separator.

Is there any plan to support this?

### PR DESCRIPTION
**Pull request by JimBobSquarePants**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/Fonts/pulls) open
- [x] I have verified that I am following matches the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description

Provides an implementation of the Unicode Line Breaking Algorithm UAX # 14
https://www.unicode.org/reports/tr14/tr14-37.html

- [x] Port Unicode Trie, Builder + Tests
- [x] Port Line Breaker implementation + Tests
- [x] Wire up to `TextLayout` algorithm
- [x]  Cleanup and optimization.

The port is based upon several sources indicated in the readme and passes over 7500 tests. 

There are ~70 outstanding tests which I have individually checked and they appear to be expecting the incorrect result according to the specification. This is inline with other implementations.

@tocsoft I'll have to leave you to do the actual wiring up of the `LineBreaker` as I will probably make a mistake. Here's how [RickTextKit](https://github.com/toptensoftware/RichTextKit/blob/a2733e43ba8484032adfb1defbdde41c09986e7f/Topten.RichTextKit/TextBlock.cs#L1312) does it.

Sorry about the additional noise but I was getting collisions with the CLR `BinaryReader` class.

Fixes #103

### CODE REVIEW

**Comment by tocsoft** [comment]
@JimBobSquarePants done.... I've integrated it the layout code, made a minor change to the line breaker code to process base don a `Memory<int>` rather than `int[]`

**Comment by JimBobSquarePants** [comment]
@tocsoft Fantastic! I'll give the code a final cleanup tonight then 👍

**Comment by JimBobSquarePants** [comment]
@tocsoft Have done the cleanup so ready for review. Left the constants naming format as-is for now. 

Spotted your new `IsWhiteSpace` is not being called by anything though?

**Comment by tocsoft** [comment]
woops I meant to take that back out again... I started a slightly more in depth change than was actually needed but changed my mind and forgot to remove that again before pushing.

**Review by tocsoft — APPROVED** [review]

**Pull request merged**
