### PR TITLE
Fix out of range exception in typographic utils.

### LINKED ISSUE #298: TextLayout.ProcessText throws an unhandled exception while using Style Script font with specific text
**Description**
I found a weird bug that occurs while using Style Script font and a specific text. An ArgumentOutOfRangeException is thrown.

**Steps to Reproduce**
```csharp
var content = "Please enter the text";

var fontFamilies = new FontCollection();

var fontFamily = fontFamilies.Add(@"<full path>\Style Script.ttf");

var font = fontFamily.CreateFont(16, FontStyle.Regular);

var renderOptions = new TextOptions(font)
{
    Dpi = 96,
    WrappingLength = 0f,
    VerticalAlignment = VerticalAlignment.Top,
    HorizontalAlignment = HorizontalAlignment.Left,
    KerningMode = KerningMode.Auto
};

var textBox = TextLayout.ProcessText(content.AsSpan(), renderOptions);
```
            
However, no exception is thrown if `content = "enter the text"`

**System Configuration**

- Fonts version: 1.0.0-beta18.2
- Other Six Labors packages and versions: none
- Environment (Operating system, version and so on): Win10
- .NET Framework version: .Net 6.0

I attached the font that I am using:
[Style Script.zip](https://github.com/SixLabors/Fonts/files/9525899/Style.Script.zip)

### LINKED ISSUE #302: TextMeasurer.TryMeasureCharacterBounds exception on Arial font with specific RTL text
### Description
I found a bug that occurs while using Arial font and a specific Arabic text. 
An ArgumentOutOfRangeException is thrown.
"Index was out of range. Must be non-negative and less than the size of the collection. Arg_ParamName_Name"
at SixLabors.Fonts.GlyphSubstitutionCollection.GetGlyphShapingData(int index)

### Steps to Reproduce

 ```
  var content = "فِيلْمٌ";
  var fontFamilies = new FontCollection();
  var fontFamily = fontFamilies.Add(@"<full path>\Arial.ttf");
  var font = fontFamily.CreateFont(16, SixLabors.Fonts.FontStyle.Regular);
  var renderOptions = new TextOptions(font);
  SixLabors.Fonts.TextMeasurer.TryMeasureCharacterBounds(content, renderOptions, out var characterBoundsAll);
```
However, no exception is thrown if content = "فِيلْمٌ"

### System Configuration
Fonts version: current source code
Other Six Labors packages and versions: none
Environment (Operating system, version and so on): Win10
.NET Framework version: .Net 6.0
I attached the font that I am using:

[arial.zip](https://github.com/SixLabors/Fonts/files/9659802/arial.zip)

### PR DESCRIPTION
**Pull request by JimBobSquarePants**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/Fonts/pulls) open
- [x] I have verified that I am following matches the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [ ] I have provided test coverage for my change (where applicable)

### Description

Fixes #298 
Fixes #302 

Also fixes a layout issue for marks I spotted when rendering the test text where we were moving them vertically in the wrong direction. Line rendering was broken also. 

enter the text

@tocsoft I noticed something a bit weird with the first sample where the top of the text is slightly cut off. This is due to the min Y bounds having a negative value (read from the glyph entry and not altered). 

I haven't attempted a workaround as I'm not sure what the best approach would be. I could maybe capture the min Y when breaking lines and offset accordingly.

### CODE REVIEW

**Comment by JimBobSquarePants** [comment]
System.Drawing clips that particular text even worse since it always adds [leading and end spacing of 1/6em](https://stackoverflow.com/a/6404811/427899). 

```c#
using Font font = new Font("Arial", 16);
using Graphics graphics = Graphics.FromHwnd(IntPtr.Zero);

SizeF size = graphics.MeasureString(input, font, Point.Empty, StringFormat.GenericTypographic).Dump();
using Bitmap image = new Bitmap((int)Math.Ceiling(size.Width), (int)Math.Ceiling(size.Height));
using Graphics graphics2 = Graphics.FromImage(image);
using Brush brush = new SolidBrush(Color.White);
graphics2.Clear(Color.Black);
graphics2.DrawString(input, font, brush, Point.Empty);
image.Save(@"C:\Users\james\Desktop\sd.png", ImageFormat.Png);
```

sd

Windows Forms `TextRenderer` type seems to include that information but still clips the image vertically.
sd

I'm not going to waste time attempting to handle it.

**Comment by mhmd-azeez** [comment]
Hello @JimBobSquarePants, if you don't mind giving me a rough outline of how to test these changes, I will try to test it on a couple of Kurdish fonts

**Comment by JimBobSquarePants** [comment]
Thanks @mhmd-azeez  The best thing to do is to use the sample project as a scratchpad to test out a few things. I'm just writing a test at the moment that will at least ensure coverage of these changes.

**Comment by mhmd-azeez** [comment]
I ran the sample on main and got a `System.ArgumentOutOfRangeException` in `GlyphSubstitutionCollection`.`GetGlyphShapingData` for `"فِيلْمٌ"` with Arial and `"بِسْمِ ٱللَّهِ ٱلرَّحْمَٟنِ ٱلرَّحِيمِ"` using Segoe UI (and Tahoma). I ran the code again on this branch and didn't get any exceptions. I also looked at the output folder and it seems to be correct:
بِسْمِ ٱللَّهِ ٱلرَّحْمَٟنِ ٱلرَّحِيمِ

فِيلْمٌ

But my arial is different from your Arial, here is how it's rendered in notepad:
image

I also tried out a couple of other fonts:
```
FontFamily arabic2 = SystemFonts.Get("Noto Naskh Arabic");
FontFamily arabic3 = SystemFonts.Get("Vazirmatn");

RenderText(arabic2, "دۆ دێرین چیا گڤ ڕەنگین", pointSize: 20);
RenderText(arabic3, "دۆ دێرین چیا گڤ ڕەنگین", pointSize: 20);
```
Which are also properly rendered:
Vazirmatn:
دۆ دێرین چیا گڤ ڕەنگین

Noto Naskh Arabic
دۆ دێرین چیا گڤ ڕەنگین

However, Noto Naskh's rendering of `"بِسْمِ ٱللَّهِ ٱلرَّحْمَٟنِ ٱلرَّحِيمِ"` is not ideal:
بِسْمِ ٱللَّهِ ٱلرَّحْمَٟنِ ٱلرَّحِيمِ

This is how it's rendered in notepad:
image

**Comment by JimBobSquarePants** [comment]
>However, Noto Naskh's rendering of "بِسْمِ ٱللَّهِ ٱلرَّحْمَٟنِ ٱلرَّحِيمِ" is not ideal:

I'll definitely have to investigate that. Thanks!

**Comment by JimBobSquarePants** [comment]
@mhmd-azeez I got a copy of Noto Naskh Arabic from [Google Fonts](https://fonts.google.com/noto/specimen/Noto+Naskh+Arabic) and rendered it using this branch. Here's my output. Are you sure you had the right branch running in your final test?

بِسْمِ ٱللَّهِ ٱلرَّحْمَٟنِ ٱلرَّحِيمِ


بِسْمِ ٱللَّهِ ٱلرَّحْمَٟنِ ٱلرَّحِيمِ

**Comment by JimBobSquarePants** [comment]
>Sorry for sending you on a wild goose chase.

No worries at all! I'm gonna merge this then. Thanks for your help!

**Pull request merged**
