### PR TITLE
Speed up Unicode Data lookups and remove reflection.

### LINKED ISSUE #279: UnicodeData class is not working without reflection
Simple call to `UnicodeData.GetBidiData` produce error in NativeAOT reflection-free mode. Even reflection-free mode is niche, would be good somehow provide workaround for these scenarios.

Underlying issues is 
https://github.com/SixLabors/Fonts/blob/034a440aece357341fcc6b02db58ffbe153e54ef/src/SixLabors.Fonts/Unicode/UnicodeData.cs#L45-L48

Embedded resources unlikely will even work in reflection-free mode for NativeAOT so maybe would be possible provide some additional API which provide additional sources for these data, maybe from extenally supplied `Stream`?

### PR DESCRIPTION
**Pull request by JimBobSquarePants**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/Fonts/pulls) open
- [x] I have verified that I am following matches the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description

This PR does a couple of things.

- Removes reflection from UnicodeTrie reading. Fixes #279 
- Removes bounds checks when performing Unicode property lookups. Touches #268 
- Adds a benchmark project

I chose to remove the compression from the trie packing for performance since the binaries do not grow out of hand and the benefit is great. @Gillibald maybe this is something to consider for Avalonia?

There's no before/after benchmarks unfortunately because I added them as an afterthought, however I took a sampling snapshot early in the process. As you can see, loading Unicode data is no longer a hotspot.

Before
image

After
image

I don't want to go crazy optimizing much further in this PR but will have a good scan through the sampling data to see if there's some low hanging fruit at another time.

CC @Sergio0694 @kant2002 @0xced

### CODE REVIEW

**Comment by Gillibald** [comment]
Nice work @JimBobSquarePants

**Comment by kant2002** [comment]
I'm not sure how do you get trie files, but I think it's better to keep source trie files in source control and document generation process. I understand that nobody want run file generation process on the build, but that process easy to forget, and maybe somebody would like to improve it, so better to have source files around. 
Or maybe I miss something in the changes ?

**Comment by JimBobSquarePants** [comment]
Thanks @Gillibald your idea to create classes was a great one!

@kant2002 The trie files are created via the Generator project and simply contained a header and the parsed bytes. That project reads a bunch of Unicode spec data files and creates the output.

Here's the project in the `main` branch.
https://github.com/SixLabors/Fonts/tree/main/src/UnicodeTrieGenerator

If you look at `Generator.cs` in this PR we're simply switching out the file generation, instead opting to create classes containing the trie data. All the source files required to create those classes are in the solution.

We definitely do not need to build them every time, though the process is pretty quick since the spec files are stored locally. We actually won't need to build these again until Unicode 15 is released and that will require a dedicated PR to do so there's no opportunity to forget.

**Comment by kant2002** [comment]
@JimBobSquarePants thanks for explanation. Yeah, now it make sense to me. Thanks you for caring about such niche workloads :smile:

**Comment by Gillibald** [comment]
I will adapt your changes for Avalonia. Really appreciate your work.

**Review by tocsoft — APPROVED** [review]

**Comment by DaZombieKiller** [comment]
I just thought it'd be worth pointing out that the `UnicodeTrie`-related code won't work on big endian systems (and will potentially fail or throw `DataMisalignedException` on systems where aligned access is required). Something more along the lines of this would solve both of those issues:
```cs
struct UnicodeTrieHeader
{
    public int HighStart;
    public uint ErrorValue;
    public int DataLength;
}

// ...

readonly uint[] data;
readonly int highStart;
readonly uint errorValue;

public UnicodeTrie(ReadOnlySpan<byte> rawData)
{
    // MemoryMarshal.Read instead of MemoryMarshal.Cast/Unsafe.As
    // because it performs an unaligned read and a bounds check.
    var header = MemoryMarshal.Read<UnicodeTrieHeader>(rawData);

    if (!BitConverter.IsLittleEndian)
    {
        header.HighStart  = BinaryPrimitives.ReverseEndianness(header.HighStart);
        header.ErrorValue = BinaryPrimitives.ReverseEndianness(header.ErrorValue);
        header.DataLength = BinaryPrimitives.ReverseEndianness(header.DataLength);
    }

    highStart  = header.HighStart;
    errorValue = header.ErrorValue;
    data       = new uint[header.DataLength / sizeof(uint)];

    // Avoid MemoryMarshal.Cast because we don't know if the rawData buffer is aligned
    // to uint, which would potentially throw DataMisalignedException if it weren't.
    rawData[Unsafe.SizeOf<UnicodeTrieHeader>()..].CopyTo(MemoryMarshal.AsBytes(data.AsSpan()));

    if (!BitConverter.IsLittleEndian)
    {
        for (int i = 0; i < data.Length; i++)
        {
            data[i] = BinaryPrimitives.ReverseEndianness(data[i]);
        }
    }
}
```

**Comment by TechPizzaDev** [comment]
The data is coming from the `ReadOnlySpan<byte>` constants isn't it? That means that casting the bytes (which are most likely little-endian) into integers will break on big-endian.

**Comment by JimBobSquarePants** [comment]
Ooh. You're right! The endianness definitely matters since it's a compiled constant. I'll update unless you want to create a PR @DaZombieKiller ?

**Comment by DaZombieKiller** [comment]
@JimBobSquarePants Sure! Opened one here: https://github.com/SixLabors/Fonts/pull/284

**Pull request merged**
